name: Update Locales

on:
  # schedule:
  #   # run every wednesday at 13:00
  #   - cron: 00 13 * * 3
  workflow_dispatch:

jobs:
  update-locales:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update submodule
        run: git submodule update --remote packages/client/components/i18n/locales
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Stoat CI
          author_email: stoat-ci@users.noreply.github.com # TODO-STOAT-WEB
          message: "chore: update locale strings"
